# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8898e7e4e5f4b70dacabdce5c0f08034f68a6eb9d87d75da0e4f18879f8a5046331001eedee33ebfecf896634e486730aa202aaabdc242a8a81e0733ddd884e

test:
  secret_key_base: f8410386e13d2f04920e997308574a0c9da952ddc6a22bee1a26af3ca2ca7ea4616b4fbff339d1ad02687bcf0dbed4c883d12f80b71b9517e20ba97a17731fa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
